name: Create error report from Issue

on:
  issues:
    types: [opened]

jobs:
  generate-md:
    if: contains(github.event.issue.labels.*.name, 'error-log')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set variables
        id: vars
        run: |
          RAW_TITLE="${{ github.event.issue.title }}"
          TITLE=$(echo "$RAW_TITLE" | sed -E 's/^\[.*\]\s*//')
          SAFE_TITLE=$(echo "$TITLE" | tr ' ' '_' | tr -cd '[:alnum:]_-')
          echo "title=$TITLE" >> $GITHUB_OUTPUT
          echo "safe_title=$SAFE_TITLE" >> $GITHUB_OUTPUT

      - name: Create markdown file
        run: |
          mkdir -p error-report
          FILE="error-report/${{ steps.vars.outputs.safe_title }}.md"
          echo "# ${{ steps.vars.outputs.title }}" > "$FILE"
          echo "" >> "$FILE"
          echo "${{ github.event.issue.body }}" >> "$FILE"

      - name: Commit and push
        run: |
          git config user.name "mayo-camp"
          git config user.email "m.naoi.sework@gmail.com"
          git add error-report/
          git commit -m "Add error report: ${{ steps.vars.outputs.title }}"
          git push
